CREATE TABLE tickets (
    id SERIAL PRIMARY KEY,
    ticket_number INTEGER,  -- Add this column if ticketNumber is not part of the ticket data
    row1_col1 INTEGER,
    row1_col2 INTEGER,
    row1_col3 INTEGER,
    row1_col4 INTEGER,
    row1_col5 INTEGER,
    row1_col6 INTEGER,
    row1_col7 INTEGER,
    row1_col8 INTEGER,
    row1_col9 INTEGER,
    row2_col1 INTEGER,
    row2_col2 INTEGER,
    row2_col3 INTEGER,
    row2_col4 INTEGER,
    row2_col5 INTEGER,
    row2_col6 INTEGER,
    row2_col7 INTEGER,
    row2_col8 INTEGER,
    row2_col9 INTEGER,
    row3_col1 INTEGER,
    row3_col2 INTEGER,
    row3_col3 INTEGER,
    row3_col4 INTEGER,
    row3_col5 INTEGER,
    row3_col6 INTEGER,
    row3_col7 INTEGER,
    row3_col8 INTEGER,
    row3_col9 INTEGER
);
